// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElLink: typeof import('element-plus/es')['ElLink']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElTimeline: typeof import('element-plus/es')['ElTimeline']
  const ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
}
export {}
